- .changeset/heavy-teachers-drum.md
- packages/authentication/README.md
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.m
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
- packages/authentication/src/definitions.ts
- packages/authentication/src/web.ts
> feat(authentication): support Firebase Emulator

- packages/authentication/README.md
Fix minor typo on the authentication's document.
> docs(authentication): fix typo

- .github/workflows/needs-triage.yml
> ci: add `needs-triage` workflow

- .changeset/gold-cameras-cry.md
- packages/analytics/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/analytics/FirebaseAnalytics.java
- packages/analytics/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/analytics/FirebaseAnalyticsPlugin.java
- packages/analytics/ios/Plugin/FirebaseAnalytics.swift
- packages/analytics/src/web.ts
> fix(analytics): run `setCurrentScreen` in the main thread

- packages/authentication/docs/setup-google.md
> docs(authentication): update reference to deprecated package

- .changeset/fuzzy-paws-guess.md
- packages/analytics/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/analytics/FirebaseAnalyticsPlugin.java
> fix(analytics): `screenClassOverride` has been ignored on Android

- .changeset/poor-planets-wave.md
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/FacebookAuthProviderHandler.java
- packages/authentication/ios/Plugin/Handlers/FacebookAuthProviderHandler.swift
> fix(authentication): `accessToken` was returned as `idToken`

- packages/authentication/README.md
> docs(authentication): remove unnecessary space

- .changeset/rare-houses-hear.md
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.m
> fix(authentication): add `removeAllListeners` method

- .changeset/khaki-needles-share.md
- packages/messaging/src/definitions.ts
> fix(messaging): typescript definitions

- .changeset/fuzzy-glasses-think.md
- package-lock.json
- packages/messaging/BREAKING.md
- packages/messaging/README.md
- packages/messaging/ios/Plugin/FirebaseMessaging.swift
- packages/messaging/ios/Plugin/FirebaseMessagingHelper.swift
- packages/messaging/ios/Plugin/FirebaseMessagingPlugin.swift
- packages/messaging/src/definitions.ts
> fix(messaging)!: receive background notifications on iOS

- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/AppleAuthProviderHandler.java
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/FacebookAuthProviderHandler.java
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/GoogleAuthProviderHandler.java
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/OAuthProviderHandler.java
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/PlayGamesAuthProviderHandler.java
- packages/authentication/ios/Plugin/Handlers/OAuthProviderHandler.swift
- packages/authentication/src/web.ts
> refactor(authentication): minor changes

- .changeset/breezy-balloons-kneel.md
- packages/messaging/src/web.ts
> fix(messaging): `messaging/unsupported-browser` error

- .changeset/forty-falcons-attend.md
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
> fix(authentication): provide access token for Twitter

- .changeset/chilly-rings-call.md
- packages/authentication/ios/Plugin/Handlers/OAuthProviderHandler.swift
- packages/messaging/README.md
- packages/messaging/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/messaging/FirebaseMessagingPlugin.java
- packages/messaging/ios/Plugin/FirebaseMessaging.swift
- packages/messaging/ios/Plugin/FirebaseMessagingHelper.swift
- packages/messaging/ios/Plugin/FirebaseMessagingPlugin.m
- packages/messaging/ios/Plugin/FirebaseMessagingPlugin.swift
- packages/messaging/src/definitions.ts
- packages/messaging/src/web.ts
> feat(messaging): add `isSupported` method

- .changeset/tender-queens-pull.md
- README.md
- packages/analytics/BREAKING.md
- packages/app/BREAKING.md
- packages/authentication/BREAKING.md
- packages/authentication/docs/setup-facebook.md
- packages/crashlytics/BREAKING.md
- packages/performance/BREAKING.md
> docs(authentication): add missing `BREAKING.md` file

- .changeset/young-clouds-talk.md
- packages/messaging/src/definitions.ts
> fix(messaging): `GetTokenOptions` parameter is now optional

- packages/analytics/README.md
- packages/app/README.md
- packages/authentication/README.md
- packages/crashlytics/README.md
- packages/messaging/README.md
- packages/performance/README.md
> docs: add Java 11 hint

- .changeset/breezy-apes-press.md
- packages/messaging/ios/Plugin/FirebaseMessaging.swift
- packages/messaging/ios/Plugin/FirebaseMessagingPlugin.swift
> fix(messaging): initial `tokenReceived` event contains invalid token value

- .changeset/odd-seahorses-pump.md
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/FacebookAuthProviderHandler.java
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/GoogleAuthProviderHandler.java
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/PhoneAuthProviderHandler.java
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/PlayGamesAuthProviderHandler.java
> fix(authentication): `NullPointerException` on Android

- .changeset/gold-rockets-teach.md
- packages/authentication/src/web.ts
> fix(authentication): `customParameters` is not applied on Web

- .changeset/pink-adults-think.md
- packages/authentication/README.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.m
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
- packages/authentication/src/definitions.ts
- packages/authentication/src/web.ts
> feat(authentication): add `tenantId` support

- .changeset/shiny-owls-fold.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/handlers/PlayGamesAuthProviderHandler.java
> fix(authentication): `serverAuthCode` is null

- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
> fix(authentication): add `skipNativeAuth` check for `signInWithEmailLink`

- packages/performance/README.md
Usage Block
had old API of
setPerformanceCollectionEnabled()
and 
isPerformanceCollectionEnabled()
> docs(performance): update usage section

- packages/authentication/README.md
- packages/authentication/src/definitions.ts
> docs(authentication): `customParameters` and `scopes` support

- .changeset/thin-queens-learn.md
- packages/authentication/README.md
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationHelper.swift
- packages/authentication/ios/Plugin/Handlers/AppleAuthProviderHandler.swift
- packages/authentication/src/definitions.ts
> feat(authentication): return `authorizationCode` on Apple Sign-In

- .changeset/tender-bulldogs-punch.md
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
- packages/messaging/ios/Plugin/FirebaseMessagingPlugin.swift
> fix(ios): `getConfigValue` is deprecated

- packages/authentication/ios/Podfile
> build(authentication): set `CODE_SIGNING_ALLOWED` to `NO` for iOS

- packages/authentication/README.md
- packages/authentication/docs/firebase-js-sdk.md
> docs(authentication): update Firebase JS SDK docs for Email Link

- .changeset/odd-frogs-talk.md
- packages/authentication/android/build.gradle
> fix(authentication): update Facebook Login SDK

- packages/authentication/README.md
- packages/authentication/src/definitions.ts
- packages/authentication/src/web.ts
> fix(authentication): add missing `linkWithGameCenter` declaration

- packages/analytics/README.md
See https://github.com/capawesome-team/capacitor-firebase/blob/fadf36b317207d54949828b0c6cf361de253f17e/packages/analytics/android/build.gradle#L6
___
> docs(analytics): update `firebaseAnalyticsVersion` in `README.md`

- packages/messaging/README.md
> docs(messaging): update installation section regarding `FirebaseAppDelegateProxyEnabled`

- .changeset/gold-buttons-dance.md
- packages/authentication/README.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/handlers/PhoneAuthProviderHandler.java
- packages/authentication/src/definitions.ts
> feat(authentication): resend sms verification code on Android

- packages/app-check/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/appcheck/FirebaseAppCheckPlugin.java
> fix(app-check): resolve calls on Android

- .changeset/twenty-bears-attack.md
- packages/authentication/README.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.m
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
- packages/authentication/src/definitions.ts
- packages/authentication/src/web.ts
> feat(authentication): add `deleteUser` method

- .changeset/big-llamas-kiss.md
- packages/authentication/README.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.m
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
- packages/authentication/src/definitions.ts
- packages/authentication/src/web.ts
> feat(authentication): add `reload` method

- .changeset/nasty-coins-ring.md
- packages/remote-config/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/remoteconfig/FirebaseRemoteConfigPlugin.java
> fix(remote-config): minimum fetch interval in seconds use integer

- docs/firebase-setup.md
- packages/analytics/README.md
- packages/app-check/README.md
- packages/app/README.md
- packages/authentication/README.md
- packages/messaging/README.md
- packages/performance/README.md
- packages/remote-config/README.md
Resolves https://github.com/capawesome-team/capacitor-firebase/issues/205#issuecomment-1425852653
> docs: add `firebase-setup.md`

- .changeset/proud-onions-pump.md
- packages/analytics/README.md
- packages/analytics/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/analytics/FirebaseAnalytics.java
- packages/analytics/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/analytics/FirebaseAnalyticsPlugin.java
- packages/analytics/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/analytics/GetAppInstanceIdCallback.java
- packages/analytics/ios/Plugin/FirebaseAnalytics.swift
- packages/analytics/ios/Plugin/FirebaseAnalyticsPlugin.m
- packages/analytics/ios/Plugin/FirebaseAnalyticsPlugin.swift
- packages/analytics/src/definitions.ts
- packages/analytics/src/web.ts
> feat(analytics): add method `getAppInstanceId`

- packages/authentication/docs/firebase-js-sdk.md
> docs(authentication): add method `getFirebaseAuth`

- packages/analytics/package.json
- packages/app-check/package.json
- packages/app/package.json
- packages/authentication/package.json
- packages/crashlytics/package.json
- packages/messaging/package.json
- packages/performance/package.json
- packages/remote-config/package.json
> chore(deps): make `firebase` as a peer dependency optional

- .changeset/warm-melons-wink.md
- packages/messaging/README.md
- packages/messaging/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/messaging/FirebaseMessaging.java
- packages/messaging/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/messaging/FirebaseMessagingHelper.java
- packages/messaging/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/messaging/FirebaseMessagingPlugin.java
- packages/messaging/ios/Plugin/FirebaseMessagingPlugin.m
- packages/messaging/ios/Plugin/FirebaseMessagingPlugin.swift
- packages/messaging/src/definitions.ts
- packages/messaging/src/web.ts
> feat(messaging): notification channels

- .changeset/wild-avocados-exist.md
- packages/analytics/ios/Plugin/FirebaseAnalytics.swift
> fix(analytics): allow screen name to be set without screen class and vice-versa

- .changeset/famous-weeks-cover.md
- packages/remote-config/ios/Plugin/FirebaseRemoteConfigPlugin.swift
> fix(remote-config): call resolved too early

- .changeset/three-lions-mix.md
- packages/authentication/ios/Plugin/Handlers/AppleAuthProviderHandler.swift
> feat(authentication): pass `fullName` (Apple) to Firebase iOS SDK

- .changeset/gorgeous-queens-juggle.md
- packages/messaging/README.md
- packages/messaging/android/src/main/AndroidManifest.xml
- packages/messaging/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/messaging/FirebaseMessagingPlugin.java
- packages/messaging/src/definitions.ts
> feat(messaging): support Android 13+ notification permission

- .changeset/clever-days-press.md
- packages/authentication/docs/firebase-js-sdk.md
> Update firebase-js-sdk Twitter example docs 

- .changeset/ten-icons-laugh.md
- package-lock.json
- packages/analytics/package.json
- packages/app-check/package.json
- packages/app/package.json
- packages/authentication/package.json
- packages/messaging/package.json
- packages/performance/package.json
- packages/remote-config/package.json
> feat: support Firebase JS SDK 10

- .changeset/healthy-seahorses-cheer.md
- packages/authentication/README.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.m
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
- packages/authentication/src/definitions.ts
- packages/authentication/src/web.ts
> feat(authentication): add method `setPersistence`

- .changeset/new-lemons-whisper.md
- packages/authentication/README.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationHelper.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/handlers/AppleAuthProviderHandler.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/handlers/FacebookAuthProviderHandler.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/handlers/GoogleAuthProviderHandler.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/handlers/OAuthProviderHandler.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/handlers/PlayGamesAuthProviderHandler.java
- packages/authentication/ios/Plugin.xcodeproj/project.pbxproj
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationHelper.swift
- packages/authentication/ios/Plugin/Handlers/GoogleAuthProviderHandler.swift
- packages/authentication/src/definitions.ts
Related to https://github.com/capawesome-team/capacitor-firebase/discussions/433
> feat(authentication): support `serverAuthCode` for Google Sign-in

- packages/authentication/README.md
- packages/firestore/README.md
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestore.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestorePlugin.java
- packages/firestore/ios/Plugin/FirebaseFirestore.swift
- packages/firestore/ios/Plugin/FirebaseFirestorePlugin.swift
- packages/firestore/src/definitions.ts
- packages/firestore/src/web.ts
> feat(firestore): add method `clearPersistence`

- packages/authentication/docs/firebase-js-sdk.md
fix invalid parameter in credential function inside firebase-js-sdk.md
> fix invalid parameter in credential function (Docs)

- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestoreHelper.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/options/AddDocumentOptions.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/options/SetDocumentOptions.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/options/UpdateDocumentOptions.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/results/GetCollectionGroupResult.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/results/GetDocumentResult.java
> feat(firestore): support all data types

- packages/firestore/README.md
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestoreHelper.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/constraints/QueryFieldFilterConstraint.java
- packages/firestore/ios/Plugin/Classes/Constraints/QueryFieldFilterConstraint.swift
- packages/firestore/src/definitions.ts
> feat(firestore): support all `QueryOperator`

- .changeset/two-beds-impress.md
- packages/authentication/README.md
- packages/authentication/src/definitions.ts
- packages/authentication/src/web.ts
Related to https://github.com/capawesome-team/capacitor-firebase/discussions/460
> feat(authentication): add option `scheme` to `useEmulator` method

- .changeset/tame-parents-burn.md
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestore.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/results/GetDocumentResult.java
> fix(firestore): `NullPointerException` in `getDocument(...)` on Android

- .changeset/orange-swans-shout.md
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/Handlers/AppleAuthProviderHandler.swift
- packages/authentication/ios/Plugin/Handlers/FacebookAuthProviderHandler.swift
- packages/authentication/ios/Plugin/Handlers/GameCenterAuthProviderHandler.swift
- packages/authentication/ios/Plugin/Handlers/GoogleAuthProviderHandler.swift
- packages/authentication/ios/Plugin/Handlers/OAuthProviderHandler.swift
> fix(authentication): `displayName` was not returned on Apple sign-in

- packages/analytics/CapacitorFirebaseAnalytics.podspec
- packages/app-check/CapacitorFirebaseAppCheck.podspec
- packages/app/CapacitorFirebaseApp.podspec
- packages/authentication/CapacitorFirebaseAuthentication.podspec
- packages/crashlytics/CapacitorFirebaseCrashlytics.podspec
- packages/firestore/CapacitorFirebaseFirestore.podspec
- packages/messaging/CapacitorFirebaseMessaging.podspec
- packages/performance/CapacitorFirebasePerformance.podspec
- packages/remote-config/CapacitorFirebaseRemoteConfig.podspec
- packages/storage/CapacitorFirebaseStorage.podspec
Related to https://github.com/capacitor-community/firebase-crashlytics/pull/80
> chore(ios): allow patch and minor updates for dependencies

- .changeset/fluffy-cooks-behave.md
- packages/authentication/README.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/classes/LinkWithPhoneNumberOptions.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/classes/SignInWithPhoneNumberOptions.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/handlers/PhoneAuthProviderHandler.java
- packages/authentication/docs/firebase-js-sdk.md
- packages/authentication/src/definitions.ts
> feat(authentication): add `timeout` option to `signInWithPhoneNumber(…)`

- .changeset/lazy-dots-camp.md
- packages/firestore/src/web.ts
> fix(firestore): `getCollectionGroup(...)` returns no data

- .changeset/afraid-balloons-sip.md
- packages/authentication/android/build.gradle
See https://github.com/firebase/firebase-android-sdk/issues/5638#issuecomment-1900834491
> feat(authentication): update `com.google.firebase:firebase-auth` to version `22.3.1`

- .changeset/healthy-shirts-occur.md
- packages/analytics/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/analytics/FirebaseAnalytics.java
- packages/app-check/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/appcheck/FirebaseAppCheck.java
- packages/app/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/capawesome/FirebaseAppPlugin.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/crashlytics/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/crashlytics/FirebaseCrashlytics.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestore.java
- packages/messaging/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/messaging/FirebaseMessaging.java
- packages/remote-config/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/remoteconfig/FirebaseRemoteConfig.java
- packages/storage/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/storage/FirebaseStorage.java
> feat: support dynamic Firebase config

- packages/authentication/README.md
Persistence is broken if running code from examples. As it turns out, because of the error in the example code.
> Fixing a persistence  error

- .changeset/ten-ants-nail.md
- packages/storage/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/storage/FirebaseStoragePlugin.java
> fix(storage): add `null` check to `updateMetadata(...)` on Android

- .changeset/fair-vans-do.md
- packages/storage/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/storage/FirebaseStorageHelper.java
> fix(storage): `uploadFile(...)` causes `NullPointerException` on Android

- .changeset/gold-tigers-judge.md
- packages/analytics/BREAKING.md
- packages/analytics/android/build.gradle
- packages/app-check/BREAKING.md
- packages/app-check/android/build.gradle
- packages/app/BREAKING.md
- packages/app/android/build.gradle
- packages/authentication/BREAKING.md
- packages/authentication/android/build.gradle
- packages/crashlytics/BREAKING.md
- packages/crashlytics/android/build.gradle
- packages/firestore/BREAKING.md
- packages/firestore/android/build.gradle
- packages/messaging/BREAKING.md
- packages/messaging/android/build.gradle
- packages/performance/BREAKING.md
- packages/performance/android/build.gradle
- packages/remote-config/BREAKING.md
- packages/remote-config/android/build.gradle
- packages/storage/BREAKING.md
- packages/storage/android/build.gradle
> chore(deps)!: update Android SDKs

- .changeset/neat-bikes-bathe.md
- package-lock.json
- packages/analytics/BREAKING.md
- packages/analytics/package.json
- packages/app-check/BREAKING.md
- packages/app-check/package.json
- packages/app/BREAKING.md
- packages/app/package.json
- packages/authentication/BREAKING.md
- packages/authentication/package.json
- packages/crashlytics/BREAKING.md
- packages/crashlytics/package.json
- packages/firestore/BREAKING.md
- packages/firestore/package.json
- packages/messaging/BREAKING.md
- packages/messaging/package.json
- packages/performance/BREAKING.md
- packages/performance/package.json
- packages/remote-config/BREAKING.md
- packages/remote-config/package.json
- packages/storage/BREAKING.md
> chore(deps): update the `firebase` dependency to `10.9.0`

- packages/crashlytics/README.md
In the code the default version has changed:
https://github.com/capawesome-team/capacitor-firebase/blob/afb8548bce82678474de488e7656ad91155449a0/packages/crashlytics/android/build.gradle#L6
> Update README.md to follow what is in the code

- .changeset/brown-grapes-visit.md
- packages/analytics/README.md
- packages/analytics/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/analytics/FirebaseAnalytics.java
- packages/analytics/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/analytics/FirebaseAnalyticsHelper.java
- packages/analytics/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/analytics/FirebaseAnalyticsPlugin.java
- packages/analytics/ios/Plugin.xcodeproj/project.pbxproj
- packages/analytics/ios/Plugin/FirebaseAnalytics.swift
- packages/analytics/ios/Plugin/FirebaseAnalyticsHelper.swift
- packages/analytics/ios/Plugin/FirebaseAnalyticsPlugin.swift
- packages/analytics/src/definitions.ts
- packages/analytics/src/web.ts
> feat(analytics): add `setConsent(...)` method

- .changeset/fifty-planes-reply.md
- packages/authentication/README.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/handlers/OAuthProviderHandler.java
- packages/authentication/docs/setup-oidc.md
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.m
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
- packages/authentication/src/definitions.ts
- packages/authentication/src/web.ts
> feat(authentication): support OpenID Connect

- .changeset/gentle-balloons-march.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
See https://github.com/capawesome-team/capacitor-firebase/issues/275#issuecomment-2147756044
> fix(authentication): `NullPointerException` when `getPendingAuthResult()` is called

- .changeset/spicy-stingrays-wait.md
- packages/storage/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/storage/FirebaseStorageHelper.java
See https://github.com/capawesome-team/capacitor-firebase/issues/275#issuecomment-2149091259
> fix(storage): `JSONException` when `customMetadata` is not set

- .changeset/nasty-mayflies-help.md
- packages/analytics/CapacitorFirebaseAnalytics.podspec
- packages/analytics/ios/Podfile
- packages/app-check/CapacitorFirebaseAppCheck.podspec
- packages/app-check/ios/Podfile
- packages/app/CapacitorFirebaseApp.podspec
- packages/app/ios/Podfile
- packages/authentication/CapacitorFirebaseAuthentication.podspec
- packages/authentication/ios/Podfile
- packages/crashlytics/CapacitorFirebaseCrashlytics.podspec
- packages/crashlytics/ios/Podfile
- packages/firestore/CapacitorFirebaseFirestore.podspec
- packages/firestore/ios/Podfile
- packages/messaging/CapacitorFirebaseMessaging.podspec
- packages/messaging/ios/Podfile
- packages/performance/CapacitorFirebasePerformance.podspec
- packages/performance/ios/Podfile
- packages/remote-config/CapacitorFirebaseRemoteConfig.podspec
- packages/remote-config/ios/Podfile
- packages/storage/CapacitorFirebaseStorage.podspec
- packages/storage/ios/Podfile
See https://github.com/capawesome-team/capacitor-firebase/discussions/634#discussioncomment-9794196
> fix: update Firebase iOS SDK to 10.25

- .changeset/empty-owls-relax.md
- package-lock.json
- packages/crashlytics/ios/Plugin/FirebaseCrashlytics.swift
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestore.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestoreHelper.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestorePlugin.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/options/WriteBatchOperation.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/options/WriteBatchOptions.java
- packages/firestore/ios/Plugin.xcodeproj/project.pbxproj
- packages/firestore/ios/Plugin/Classes/Options/WriteBatchOperation.swift
- packages/firestore/ios/Plugin/Classes/Options/WriteBatchOptions.swift
- packages/firestore/ios/Plugin/FirebaseFirestore.swift
- packages/firestore/ios/Plugin/FirebaseFirestorePlugin.m
- packages/firestore/ios/Plugin/FirebaseFirestorePlugin.swift
- packages/firestore/src/definitions.ts
- packages/firestore/src/web.ts
> feat(firestore): support batched writes

- .changeset/gorgeous-doors-change.md
- packages/firestore/README.md
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestore.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestorePlugin.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/options/AddCollectionGroupSnapshotListenerOptions.java
- packages/firestore/ios/Plugin.xcodeproj/project.pbxproj
- packages/firestore/ios/Plugin/Classes/Options/AddCollectionGroupSnapshotListenerOptions.swift
- packages/firestore/ios/Plugin/FirebaseFirestore.swift
- packages/firestore/ios/Plugin/FirebaseFirestorePlugin.m
- packages/firestore/ios/Plugin/FirebaseFirestorePlugin.swift
- packages/firestore/src/definitions.ts
- packages/firestore/src/web.ts
> feat(firestore): add `addCollectionGroupSnapshotListener(...)` method

- .changeset/itchy-cobras-hunt.md
- packages/firestore/src/web.ts
> fix(firestore): handle snapshot errors on web

- packages/functions/README.md
- packages/functions/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/functions/FirebaseFunctions.java
- packages/functions/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/functions/FirebaseFunctionsPlugin.java
- packages/functions/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/functions/classes/options/CallByNameOptions.java
- packages/functions/ios/Plugin/Classes/Options/CallByNameOptions.swift
- packages/functions/ios/Plugin/FirebaseFunctions.swift
- packages/functions/ios/Plugin/FirebaseFunctionsPlugin.swift
- packages/functions/src/definitions.ts
- packages/functions/src/web.ts
> feat(functions): support Cloud Functions locations

- .changeset/dirty-games-reflect.md
- packages/authentication/README.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationHelper.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/classes/options/SendEmailVerificationOptions.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/classes/options/SendPasswordResetEmailOptions.java
- packages/authentication/ios/Plugin.xcodeproj/project.pbxproj
- packages/authentication/ios/Plugin/Classes/Options/SendEmailVerificationOptions.swift
- packages/authentication/ios/Plugin/Classes/Options/SendPasswordResetEmailOptions.swift
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationHelper.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
- packages/authentication/src/definitions.ts
- packages/authentication/src/web.ts
> feat(authentication): support `actionCodeSettings` in `sendEmailVerification(...)` and `sendPasswordResetEmail(...)`

- .changeset/lemon-geese-learn.md
- packages/functions/README.md
- packages/functions/src/definitions.ts
- packages/functions/src/web.ts
> feat(functions): add generic types

- .changeset/lazy-islands-invite.md
- packages/storage/README.md
- packages/storage/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/storage/classes/results/GetMetadataResult.java
- packages/storage/ios/Plugin/Classes/Results/GetMetadataResult.swift
- packages/storage/src/definitions.ts
- packages/storage/src/web.ts
> feat(storage): get custom metadata

- .changeset/beige-grapes-swim.md
- packages/storage/README.md
- packages/storage/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/storage/classes/results/GetMetadataResult.java
- packages/storage/ios/Plugin/Classes/Results/GetMetadataResult.swift
- packages/storage/src/definitions.ts
- packages/storage/src/web.ts
> feat(storage): get settable metadata

- packages/functions/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/functions/FirebaseFunctions.java
- packages/functions/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/functions/classes/options/CallByUrlOptions.java
> fix callByUrl method

- packages/analytics/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/analytics/FirebaseAnalyticsHelper.java
> fix(analytics): add null check

- .changeset/tidy-icons-marry.md
- packages/analytics/src/web.ts
> fix(analytics): set correct consent settings property name

- .changeset/small-flies-admire.md
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestore.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestoreHelper.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestorePlugin.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/options/AddCollectionGroupSnapshotListenerOptions.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/options/AddCollectionSnapshotListenerOptions.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/options/AddDocumentSnapshotListenerOptions.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/results/GetCollectionGroupResult.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/results/GetCollectionResult.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/results/GetDocumentResult.java
- packages/firestore/ios/Plugin/Classes/Options/AddCollectionGroupSnapshotListenerOptions.swift
- packages/firestore/ios/Plugin/Classes/Options/AddCollectionSnapshotListenerOptions.swift
- packages/firestore/ios/Plugin/Classes/Options/AddDocumentSnapshotListenerOptions.swift
- packages/firestore/ios/Plugin/Classes/Results/GetCollectionGroupResult.swift
- packages/firestore/ios/Plugin/Classes/Results/GetCollectionResult.swift
- packages/firestore/ios/Plugin/Classes/Results/GetDocumentResult.swift
- packages/firestore/ios/Plugin/FirebaseFirestore.swift
- packages/firestore/ios/Plugin/FirebaseFirestorePlugin.swift
- packages/firestore/src/definitions.ts
- packages/firestore/src/web.ts
> feat(firestore): include `metadata` property on snapshot

- .changeset/shaggy-parrots-relax.md
- packages/analytics/CapacitorFirebaseAnalytics.podspec
- packages/analytics/ios/Podfile
- packages/app-check/CapacitorFirebaseAppCheck.podspec
- packages/app-check/ios/Podfile
- packages/app/CapacitorFirebaseApp.podspec
- packages/app/ios/Podfile
- packages/authentication/CapacitorFirebaseAuthentication.podspec
- packages/authentication/ios/Podfile
- packages/crashlytics/CapacitorFirebaseCrashlytics.podspec
- packages/crashlytics/ios/Podfile
- packages/firestore/CapacitorFirebaseFirestore.podspec
- packages/firestore/ios/Podfile
- packages/functions/CapacitorFirebaseFunctions.podspec
- packages/functions/ios/Podfile
- packages/messaging/CapacitorFirebaseMessaging.podspec
- packages/messaging/ios/Podfile
- packages/performance/CapacitorFirebasePerformance.podspec
- packages/performance/ios/Podfile
- packages/remote-config/CapacitorFirebaseRemoteConfig.podspec
- packages/remote-config/ios/Podfile
- packages/storage/CapacitorFirebaseStorage.podspec
- packages/storage/ios/Podfile
> chore(ios): update Firebase pods to version `11.0`

- .changeset/shiny-starfishes-poke.md
- package-lock.json
- packages/analytics/package.json
- packages/app-check/package.json
- packages/app/package.json
- packages/authentication/package.json
- packages/firestore/package.json
- packages/functions/package.json
- packages/messaging/package.json
- packages/performance/package.json
- packages/remote-config/package.json
- packages/storage/package.json
> feat: add support for Firebase JS SDK 11

- .changeset/silver-singers-guess.md
- packages/authentication/CapacitorFirebaseAuthentication.podspec
- packages/authentication/ios/Podfile
> feat(authentication): update Facebook iOS SDK to 17.1.0

- .changeset/cuddly-bears-return.md
- packages/messaging/src/web.ts
---
Prevent the error: `Can't find variable: Notification`
> fix(messaging): check if notifications are supported before checking or requesting permission

- .changeset/nasty-students-attack.md
- packages/authentication/CapacitorFirebaseAuthentication.podspec
- packages/authentication/ios/Podfile
> fix(authentication): downgrade the Facebook iOS SDK

- .changeset/little-buses-hug.md
- packages/functions/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/functions/classes/results/CallResult.java
> fix(functions): Serialize array of arrays.

- .changeset/quiet-files-pump.md
- packages/messaging/README.md
- packages/messaging/ios/Plugin/FirebaseMessaging.swift
- packages/messaging/src/definitions.ts
> fix(messaging): request all permissions regardless of the configured presentation options

- .changeset/thick-socks-fetch.md
- packages/crashlytics/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/crashlytics/FirebaseCrashlytics.java
> fix(crashlytics): do not pass `null` to `recordException(...)`
