capawesome-team/capacitor-firebase

- .changeset/hip-masks-mix.md
- packages/analytics/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/analytics/FirebaseAnalyticsHelper.java
> fix(analytics): string parameters in `logEvent` are sent as `String` instead of the parameter value

- .changeset/light-eyes-wash.md
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/GoogleAuthProviderHandler.java
This resolves one part of #65.
> feat(authentication): provide access token for Google on Android

- .changeset/small-fishes-end.md
- packages/authentication/README.md
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationHelper.java
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/AppleAuthProviderHandler.java
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/FacebookAuthProviderHandler.java
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/GoogleAuthProviderHandler.java
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/OAuthProviderHandler.java
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/PhoneAuthProviderHandler.java
- packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/handlers/PlayGamesAuthProviderHandler.java
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationHelper.swift
- packages/authentication/ios/Plugin/Handlers/PhoneAuthProviderHandler.swift
- packages/authentication/src/definitions.ts
- packages/authentication/src/web.ts
> feat(authentication): expose `AdditionalUserInfo`

- .changeset/twelve-crabs-fetch.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
> fix(authentication): retain `authStateChangeEvent` until consumed

- .changeset/dull-steaks-count.md
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationHelper.swift
- packages/authentication/ios/Plugin/Handlers/AppleAuthProviderHandler.swift
> fix(authentication):`displayName` is missing when signing in with Apple on iOS using `skipNativeAuth`

- .changeset/spotty-tigers-laugh.md
- package-lock.json
- packages/authentication/README.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/handlers/PhoneAuthProviderHandler.java
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
- packages/authentication/ios/Plugin/Handlers/PhoneAuthProviderHandler.swift
- packages/authentication/src/definitions.ts
> feat(authentication): provide the auto-retrieved SMS verification code

- .changeset/warm-eyes-float.md
- packages/authentication/BREAKING.md
- packages/authentication/README.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.m
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
- packages/authentication/package.json
- packages/authentication/src/definitions.ts
- packages/authentication/src/web.ts
> feat(authentication): add `updateProfile` method

- .changeset/dull-keys-remain.md
- packages/analytics/BREAKING.md
- packages/analytics/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/analytics/FirebaseAnalytics.java
- packages/analytics/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/analytics/FirebaseAnalyticsPlugin.java
- packages/app-check/BREAKING.md
- packages/app-check/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/appcheck/FirebaseAppCheck.java
- packages/app-check/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/appcheck/FirebaseAppCheckPlugin.java
- packages/app/BREAKING.md
- packages/app/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/capawesome/FirebaseAppPlugin.java
- packages/authentication/BREAKING.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/crashlytics/BREAKING.md
- packages/crashlytics/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/crashlytics/FirebaseCrashlyticsPlugin.java
- packages/messaging/BREAKING.md
- packages/messaging/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/messaging/FirebaseMessaging.java
- packages/messaging/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/messaging/FirebaseMessagingPlugin.java
- packages/performance/BREAKING.md
- packages/performance/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/performance/FirebasePerformancePlugin.java
- packages/remote-config/BREAKING.md
- packages/remote-config/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/remoteconfig/FirebaseRemoteConfig.java
- packages/remote-config/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/remoteconfig/FirebaseRemoteConfigPlugin.java
> refactor: use `getMessage` instead of `getLocalizedMessage` on Android

- .changeset/spicy-turkeys-impress.md
- packages/analytics/CapacitorFirebaseAnalytics.podspec
> fix(analytics): pod `FirebaseAnalyticsWithoutAdIdSupport` does not exist

- .changeset/happy-cows-own.md
- packages/authentication/README.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationHelper.java
- packages/authentication/ios/Plugin/FirebaseAuthenticationHelper.swift
- packages/authentication/src/definitions.ts
- packages/authentication/src/web.ts
> feat(authentication): expose `providerData` and `metadata` property

- .changeset/tasty-mirrors-wave.md
- packages/authentication/README.md
- packages/authentication/android/build.gradle
This pull request updates the Firebase Authentication library for Android to 22.1.2. Using version 21 shows a message in Play Console warning the developer that the SafetyNet API will be discontinued soon:
The version 22 removed SafetyNet support for app verification during phone number authentication (see changelog [here](https://firebase.google.com/support/release-notes/android#auth_v22-0-0)). Although it is marked as a breaking change, this does not seem to affect the functionality of this plugin. SafetyNet will be discontinued soon as mentioned in their [deprecation timeline](https://developer.android.com/training/safetynet/deprecation-timeline). This link also gives information on how to migrate to the new Play Integrity …
> feat(authentication): update Firebase Auth for Android to 22.1.2

- .changeset/khaki-maps-carry.md
- packages/authentication/ios/Plugin/Handlers/PhoneAuthProviderHandler.swift
> fix(authentication): empty verification ID on phone auth

- .changeset/fifty-eels-notice.md
- packages/authentication/ios/Plugin/Handlers/OAuthProviderHandler.swift
Very simple change to fix swapped link and signIn functions for oauth flow sign in.
Close #524
Issue: 
Microsoft (and presumably other OAuth based sign in methods) were failing on iOS with a "No user signed in" error.
Swapping these functions as their names intend resolves the issue.
> fix(authentication): sign-in with oauth provider failed

- .changeset/witty-clouds-yawn.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
> fix(authentication): `authStateChange` event is not fired right after the listener is registered

- .changeset/lovely-frogs-sit.md
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/constraints/QueryCompositeFilterConstraint.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/interfaces/QueryFilterConstraint.java
> fix(firestore): only last `QueryFilterConstraint` was applied on Android

- .changeset/purple-jobs-roll.md
- packages/firestore/BREAKING.md
- packages/firestore/src/definitions.ts
> refactor(firestore): remove the `QueryDocumentSnapshot` interface

- .changeset/khaki-seals-buy.md
- packages/authentication/README.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/classes/options/FetchSignInMethodsForEmailOptions.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/classes/results/FetchSignInMethodsForEmailResult.java
- packages/authentication/ios/Plugin.xcodeproj/project.pbxproj
- packages/authentication/ios/Plugin/Classes/Options/FetchSignInMethodsForEmailOptions.swift
- packages/authentication/ios/Plugin/Classes/Results/FetchSignInMethodsForEmailResult.swift
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.m
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
- packages/authentication/src/definitions.ts
- packages/authentication/src/web.ts
> feat(authentication): add `fetchSignInMethodsForEmail(...)` method

- .changeset/blue-bats-yell.md
- packages/authentication/src/web.ts
> fix(authentication): `authStateChange` listener fires too early on the web

- .changeset/chilly-coins-smash.md
- packages/analytics/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/analytics/FirebaseAnalyticsPlugin.java
- packages/analytics/ios/Plugin/FirebaseAnalyticsPlugin.m
Closes https://github.com/capawesome-team/capacitor-firebase/issues/636
> fix(analytics): `setConsent(...)` method did not work

- .changeset/grumpy-feet-hug.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/classes/options/RevokeAccessTokenOptions.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/handlers/PhoneAuthProviderHandler.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/interfaces/EmptyResultCallback.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/interfaces/NonEmptyResultCallback.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/interfaces/ResultCallback.java
- packages/authentication/ios/Plugin.xcodeproj/project.pbxproj
- packages/authentication/ios/Plugin/Classes/Options/RevokeAccessTokenOptions.swift
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.m
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
- packages/authentication/src/definitions.ts
- packages/authentication/src/web.ts
> feat(authentication): add `revokeAccessToken(...)` method

- .changeset/nasty-insects-turn.md
- packages/authentication/src/web.ts
> fix(authentication): `updateProfile(...)` ignored the `photoUrl`

- .changeset/violet-taxis-end.md
- packages/firestore/README.md
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestore.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestorePlugin.java
- packages/firestore/ios/Plugin/FirebaseFirestore.swift
- packages/firestore/ios/Plugin/FirebaseFirestorePlugin.m
- packages/firestore/ios/Plugin/FirebaseFirestorePlugin.swift
- packages/firestore/src/definitions.ts
- packages/firestore/src/web.ts
- packages/functions/README.md
- packages/functions/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/functions/FirebaseFunctions.java
- packages/functions/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/functions/FirebaseFunctionsPlugin.java
- packages/functions/ios/Plugin/FirebaseFunctions.swift
- packages/functions/ios/Plugin/FirebaseFunctionsPlugin.m
- packages/functions/ios/Plugin/FirebaseFunctionsPlugin.swift
- packages/functions/src/definitions.ts
- packages/functions/src/web.ts
- packages/storage/README.md
- packages/storage/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/storage/FirebaseStorage.java
- packages/storage/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/storage/FirebaseStoragePlugin.java
- packages/storage/ios/Plugin/FirebaseStorage.swift
- packages/storage/ios/Plugin/FirebaseStoragePlugin.m
- packages/storage/ios/Plugin/FirebaseStoragePlugin.swift
- packages/storage/src/definitions.ts
- packages/storage/src/web.ts
> feat(emulator): add the emulator support on firestore, functions and storage packages

- .changeset/slow-news-poke.md
- packages/analytics/README.md
If you keep the old version of firebaseAnalyticsVersion = '21.2.2' in the new Capacitor 6 version it gives an error when compiling.
By default the new version of Firebase Analytics is now firebaseAnalyticsVersion = '21.5.1' but you should update it in the documentation so that you don't get an error when upgrading.
Fix: #679
> Changed the analytics version of the documentation from 21.2.2 to 21.5.1

- .changeset/soft-news-flash.md
- packages/remote-config/README.md
- packages/remote-config/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/remoteconfig/FirebaseRemoteConfig.java
- packages/remote-config/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/remoteconfig/FirebaseRemoteConfigPlugin.java
- packages/remote-config/ios/Plugin/FirebaseRemoteConfig.swift
- packages/remote-config/ios/Plugin/FirebaseRemoteConfigPlugin.m
- packages/remote-config/ios/Plugin/FirebaseRemoteConfigPlugin.swift
- packages/remote-config/src/definitions.ts
- packages/remote-config/src/web.ts
Close https://github.com/capawesome-team/capacitor-firebase/issues/687 
Close https://github.com/capawesome-team/capacitor-firebase/issues/688
--- 
Example: 
```typescript
await FirebaseRemoteConfig.setConfigSettings({
fetchTimeoutInSeconds: 10,
minimumFetchIntervalInSeconds: 0,
})
```
At first, I was thinking of adding a method that could only set fetchTimeoutInSeconds. But when I checked the Firebase SDK interface for Android, I found that it could not be set individually, so I added a method to set it all together
> feat(remote-config): add `setSettings(...)` method

- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestore.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestoreHelper.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestorePlugin.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/options/AddCollectionGroupSnapshotListenerOptions.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/options/AddCollectionSnapshotListenerOptions.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/options/AddDocumentSnapshotListenerOptions.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/results/GetCollectionGroupResult.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/results/GetCollectionResult.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/results/GetDocumentResult.java
- packages/firestore/ios/Plugin/Classes/Options/AddCollectionGroupSnapshotListenerOptions.swift
- packages/firestore/ios/Plugin/Classes/Options/AddCollectionSnapshotListenerOptions.swift
- packages/firestore/ios/Plugin/Classes/Options/AddDocumentSnapshotListenerOptions.swift
- packages/firestore/ios/Plugin/Classes/Results/GetCollectionGroupResult.swift
- packages/firestore/ios/Plugin/Classes/Results/GetCollectionResult.swift
- packages/firestore/ios/Plugin/Classes/Results/GetDocumentResult.swift
- packages/firestore/ios/Plugin/FirebaseFirestore.swift
- packages/firestore/ios/Plugin/FirebaseFirestorePlugin.swift
- packages/firestore/src/definitions.ts
- packages/firestore/src/web.ts
I've created the Android implementation based on your proposed interface. I've removed the `source` option because it is only supported on the web platform and does not exist in the Android SDK.
> feat(firestore): include metadata property on snapshot (#567)

- .changeset/thin-hornets-explain.md
- packages/crashlytics/ios/Plugin/FirebaseCrashlytics.swift
- packages/crashlytics/ios/Plugin/FirebaseCrashlyticsPlugin.swift
> fix(crashlytics): `crash(...)` method now respects message option

- .changeset/selfish-steaks-enjoy.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/handlers/GoogleAuthProviderHandler.java
This PR explicitly requests scopes when getting a Google access token post-Sign In with Google.
It looks like not requesting scopes explicitly works _most_ of the time, but not all of the time. I had two users with this bug [(nkalupahana/baseline#402)](https://github.com/nkalupahana/baseline/issues/401), and this change fixed it for them ([patch](https://github.com/nkalupahana/baseline/blob/main/patches/%40capacitor-firebase%2Bauthentication%2B6.0.0.patch)). This PR upstreams our patch.
Closes #725
> fix(authentication): explicitly request Google auth token with provided scopes on Android

- .changeset/tall-eagles-learn.md
- packages/authentication/README.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.m
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
- packages/authentication/src/definitions.ts
- packages/authentication/src/web.ts
Pull request to handle this feature request:
https://github.com/capawesome-team/capacitor-firebase/issues/739
> Added verifyBeforeUpdateEmail method to Web, iOS, Android

- .changeset/smooth-mirrors-bow.md
- package-lock.json
- packages/analytics/src/web.ts
Since I've implemented setUserId on a web project, I have less unique visitors than expected. I have some doubts of the implementation of setUserId, which currently set an empty string if we pass a null value.
According to the Firebase JS docs, null is accepted : https://firebase.google.com/docs/reference/js/analytics.md?hl=fr#setuserid_86d82f6
And iOS / Android docs says that userId must be a non empty string : https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#public-void-setuserid-string-id https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#public-void-setuserid-string-id
> fix(analytics): setUserId accepts null values

- .changeset/cuddly-baboons-add.md
- packages/functions/README.md
- packages/functions/src/definitions.ts
- packages/functions/src/web.ts
* fix useEmulator for specific region
Introduced a new property `regionOrCustomDomain` to the `UseEmulatorOptions` interface to enable specifying either a region or a custom domain for callable Firebase functions. This change facilitates greater flexibility in configuring the functions emulator based on deployment preferences. Updated related documentation to reflect these changes for clarity.
Close #765
> feat(functions): Add regionOrCustomDomain option to useEmulator.

- .changeset/eleven-hornets-joke.md
- packages/firestore/ios/Plugin/FirebaseFirestore.swift
- packages/firestore/ios/Plugin/FirebaseFirestorePlugin.swift
Close #771
Wraps the `listenerRegistrationMap` in an actor to manage the reading and writing in a thread-safe way. It is necessary because `addCollectionSnapshotListener` and `addCollectionGroupSnapshotListener` dispatch a Task in order to build the constraints but then immediately write to the `listenerRegistrationMap` within that Task.
> fix(firestore): Prevent iOS crash caused by concurrency issue

- .changeset/friendly-shoes-tell.md
- packages/firestore/README.md
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestore.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestorePlugin.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/options/GetCountFromServerOptions.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/classes/results/GetCountFromServerResult.java
- packages/firestore/ios/Plugin.xcodeproj/project.pbxproj
- packages/firestore/ios/Plugin/Classes/Options/GetCountFromServerOptions.swift
- packages/firestore/ios/Plugin/Classes/Results/GetCountFromServerResult.swift
- packages/firestore/ios/Plugin/FirebaseFirestore.swift
- packages/firestore/ios/Plugin/FirebaseFirestorePlugin.m
- packages/firestore/ios/Plugin/FirebaseFirestorePlugin.swift
- packages/firestore/src/definitions.ts
- packages/firestore/src/web.ts
> feat(firestore): add `getCountFromServer(...)` method 

- .changeset/tricky-papayas-shout.md
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestoreHelper.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestorePlugin.java
- packages/firestore/ios/Plugin/FirebaseFirestore.swift
- packages/firestore/ios/Plugin/FirebaseFirestoreHelper.swift
- packages/firestore/ios/Plugin/FirebaseFirestorePlugin.swift
- packages/storage/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/storage/FirebaseStorageHelper.java
- packages/storage/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/storage/FirebaseStoragePlugin.java
- packages/storage/ios/Plugin/FirebaseStorageHelper.swift
- packages/storage/ios/Plugin/FirebaseStoragePlugin.swift
> feat: add firestore & cloud storage error codes

- .changeset/hungry-emus-pay.md
- packages/performance/BREAKING.md
- packages/performance/src/web.ts
Throw error on all platforms when trace is not found.
Close #773
> fix(performance): inconsistent handling when trace does not exist

- .changeset/nine-dogs-double.md
- .github/workflows/ci.yml
- packages/authentication/BREAKING.md
- packages/authentication/CapacitorFirebaseAuthentication.podspec
- packages/authentication/android/build.gradle
- packages/authentication/ios/Podfile
Update facebook sdk version.
Closes: #662
> feat(auth): update Facebook Login SDK for iOS

- .changeset/breezy-hounds-chew.md
- packages/authentication/BREAKING.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationHelper.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/ios/Plugin/FirebaseAuthenticationHelper.swift
- packages/firestore/BREAKING.md
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestoreHelper.java
- packages/firestore/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/firestore/FirebaseFirestorePlugin.java
- packages/firestore/ios/Plugin/FirebaseFirestoreHelper.swift
- packages/firestore/ios/Plugin/FirebaseFirestorePlugin.swift
- packages/storage/BREAKING.md
- packages/storage/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/storage/FirebaseStoragePlugin.java
- packages/storage/ios/Plugin/FirebaseStoragePlugin.swift
> refactor: rename error codes

- .changeset/wild-pianos-check.md
- packages/app-check/ios/Plugin/FirebaseAppCheckPlugin.swift
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
- packages/authentication/src/definitions.ts
Regarding #831, the `verifyBeforeUpdateEmail()` function was added by @ewwwgiddings in #741.
After integration, I discovered that the `actionCodeSettings` parameter in `verifyBeforeUpdateEmail()` is optional according to the flow design and documentation.
Without it, a verification email will be sent without dynamic links functionality to open the link in the app.
- iOS: https://firebase.google.com/docs/reference/swift/firebaseauth/api/reference/Classes/User#/c:@M@FirebaseAuth@objc(cs)FIRUser(im)sendEmailVerificationBeforeUpdatingEmail:actionCodeSettings:completion:
- Android: https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser#verifyBeforeUpdateEmail(java.lang.String)
- Web: https://firebase.google.com/docs/reference/node/firebase.User#verifybeforeupda …
> fix(authentication): mark `actionCodeSettings` option as optional

- .changeset/rare-pigs-divide.md
- packages/messaging/ios/Plugin/FirebaseMessagingPlugin.swift
> fix(messaging): `tokenReceived` event did not always contain a token

- .changeset/happy-oranges-rush.md
- packages/authentication/README.md
- packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
- packages/authentication/docs/setup-facebook.md
- packages/authentication/ios/Plugin.xcodeproj/project.pbxproj
- packages/authentication/ios/Plugin/Classes/Results/CheckAppTrackingTransparencyPermissionResult.swift
- packages/authentication/ios/Plugin/FirebaseAuthentication.swift
- packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.swift
- packages/authentication/ios/Plugin/Handlers/FacebookAuthProviderHandler.swift
- packages/authentication/src/definitions.ts
- packages/authentication/src/web.ts
> fix(authentication): Bad `accessToken` when signing in via Facebook under iOS
